version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mkononi_db
      POSTGRES_USER: mkononi_user
      POSTGRES_PASSWORD: mkononi_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./mk_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - USE_POSTGRES=True
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./mk_backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data: